### ISSUE TITLE
Unable to load UI.

### ISSUE THREAD

**Issue by ScRumP479** [vipexv/v-vehControl#4]
![VehControl](https://github.com/vipexv/v-vehControl/assets/164339867/924e19f2-02e0-496b-a361-15c79476a078)

Latest release installed, please help!

**Comment by vipexv** [comment]
I don't have my setup rn so I'm unavailable to work on it, please record a video of you downloading the script so I can see what your downloading, also show me the contents inside of the web folder after.

**Comment by gfrast** [comment]
![image](https://github.com/vipexv/v-vehControl/assets/95580565/fdba478c-34c7-43ba-a4ec-6b4ed57d0925)
same here, since the last update...

**Comment by gfrast** [comment]
![image](https://github.com/vipexv/v-vehControl/assets/95580565/eda46442-447a-4f17-93b8-b49b59b994a9)

**Comment by vipexv** [comment]
Show me the contents inside the web folder.

**Comment by gfrast** [comment]
![image](https://github.com/vipexv/v-vehControl/assets/95580565/f183175e-ea6d-4dbc-95f5-630fc2975ee3)

**Comment by vipexv** [comment]
I don't have my setup as of currently due to personal issues but you installed a non compiled version, please download it from the releases page and the v-vehControl.zip and not the source code.

 ![image](https://github.com/vipexv/v-vehControl/assets/101529155/3697593a-ccee-4a1e-a62a-9e50690ce777)![image](https://github.com/vipexv/v-vehControl/assets/101529155/92786363-8004-4a77-9026-a1099d5c82eb)

**Comment by vipexv** [comment]
Here ![image](https://github.com/vipexv/v-vehControl/assets/101529155/585b380d-b667-46c4-b209-5124fd8f484d)

**Comment by gfrast** [comment]
now I'm blushing. sorry :D
